<div class="row static-contemporary">
    <div class="col-md-4 contemporary-text">
        <h2 class="text-center">STYLES</h3>
        <hr>
        <h1 class="text-center">CONTEMPORARY</h2>
        <p class="text-center">lorem Ipsum dolar sit amet, ius ad saperet proesent voluptaria. Dicunt voluptatum appellantur easntur</p>
    </div>
    <div class="col-md-8">
        <img src="<?php echo $this->getViewFileUrl('images/brown-sofa-resize_edited.jpg'); ?>">
    </div>
</div>
