<div class="col-md-2 col-sm-12 col-xs-12 col-12 rmi-order-2">
        <h3>Customer Care</h3>
        <div class="line"></div>
    <ul class="">
        <li><a href="<?php echo $this->getBaseUrl();?>about-us">About Us</a></li>
        <li><a href="<?php echo $this->getBaseUrl();?>shipping-info">Shipping Info</a></li>
        <li><a href="<?php echo $this->getBaseUrl();?>returns-policy">Returns and Exchanges</a></li>
    </ul>
</div>
