<div class="col-md-2 col-sm-12 col-xs-12 rmi-order-1">
        <h3>Account</h3>
        <div class="testing line"></div>
    <ul class="">
        <li><a href="<?php echo $this->getBaseUrl();?>checkout/cart/">View Cart</a></li>
        <li><a href="<?php echo $this->getBaseUrl();?>wishlist">My Wishlist</a></li>
        <li><a href="<?php echo $this->getBaseUrl();?>sales/guest/form/">Track My Order</a></li>
    </ul>
</div>
