
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-customer-care')->toHtml();?>
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-account')->toHtml();?>
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-visit-us')->toHtml();?>
<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-newsletter-socialmedia')->toHtml();?>
